# Generated by Django 4.0.3 on 2022-03-17 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctor_tb')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.patient_tb')),
            ],
        ),
    ]
